### PR TITLE
Add progress counter to prometheus output

### PR DESCRIPTION
**Pull request by telackey**
This adds (estimated) progress counters for the top-level tracked iterators by checking the current it.Path() position vs the total distance of startPath to endPath.

### CODE REVIEW

**Review by i-norden — COMMENTED** [review]
Still trying to grok this fully. 

When the traversal gets deeper into the trie, we are more likely to encounter branch nodes with (more) empty child slots and more likely to encounter extension nodes that skip over entire path segments. But as we get deeper the width of the trie also grows exponentially. Aka from root to first level there is only 1 branch node with 16 children. From first level to second level there are 16 branch nodes with 16 children each, etc. So, if I understand this code correctly, the difference from say `0x` to `0x000` will look the same as the difference between `0x000` to `0x000000` but there will be many, many more nodes to traverse going between the latter start and end position. If we assume these levels are all fully populated, which they probably are since these aren't all the deep, then there would (16+16^2+16^3) nodes to traverse in the first segment and (16^4+16^5+16^6) nodes to traverse in the second one.

**Comment by dboreham** [comment]
I think this is about "how good/bad is the estimate, really?".
It should be possible to get some pudding proof on this, since @telackey has run the code on mainnet at block height 14M.
What did the progress graph look like in that case? (big discontinuities would indicate the estimate is not good).

**Comment by telackey** [comment]
> I think this is about "how good/bad is the estimate, really?"

Yes, and I would be full open to renaming the method "estimatePathDistance" if that would help convey the intended use.  Or even "pathBreadth" as the distance is "across" rather than down.

So the goal was to provide some sort of indicator between "started" and "done", especially on a process which takes well over 24 hours.  We do have some counters on the number of different node types processed, but without goalposts, those don't communicate very much info other than that the process if still doing stuff.

With the tracked iterators, we get bounded start/end paths that usually look something like:

```
:04
0400:08
0800:0c
0c00:
```

The idea at hand is that if the tree is reasonably balanced, we should be able to gauge the current iterator position, and judge how far along it is.  In the simplest case of a single iterator, the range is `0x0:0xf`, so if it is currently at path `0x8`, you can estimate that it is 50% done.  Is the necessarily true?  No, because the tree may not be balanced, but it it is a reasonable guess.

Extrapolating it to the slightly more complicated example with 4 iterators above, I should be able to say that for an iterator processing the range `0400:08` if the current it.Path() is `06`, that it is is also about 50% done.

The wrinkle that makes the latter comparison tricky is that the paths as we observe them don't all have the same depth (eg, `0400` vs `06`), so the comparison cannot always be direct.  But we can figure out the _maximum_ number of iterations at the top-level that it would take to get from our start path (`0400`) to our end path (`08[00]`), which is 4x16 = 64, and also the maximum number if iterations it would have taken to get to our current position `0400` to `06[00]` (2x16 = 32), and gauge accordingly.

**Comment by dboreham** [comment]
@telackey if you plot the graph of "indicated %done" vs "% of eventual elapsed time" for your 14M mainnet snapshot, is it a straight line through the origin? If not how much does it deviate from that ideal line?

**Review by i-norden — APPROVED** [review]
Thanks for the detailed explanation, I wasn't thinking about it properly in the context of the actual `start` and `stop` paths we see in practice. We won't ever have `start` and `stop` pairs that span many different levels like in my example. Since it is as you said @telackey where the dissection of the trie for the different subtrie iterators is done by dividing the keyspace within the first couple of levels only and restricting the iterators to these prefix ranges, and the trie is effectively balanced, then tracking the progress this way makes a lot of sense and looks like a good estimate to me.

**Review by dboreham — APPROVED** [review]

**Comment by telackey** [comment]
I refactored the code a bit it to call it `estimateSteps`, as I thought that might better convey what it was doing.

I also found a bug while double checking some output to answer @dboreham 's question (basically under certain circumstances it could switch comparison "depths" for the last worker, eg from 0c00:nil to 0c:nil, and so give an apparent, but illusory, sudden leap in progress).  The simplest fix for that was to make the desired comparison "depth" explicit, which also has the benefit of making the logic clearer in general.

For the question of progress, unfortunately I didn't have the elapsed time output on the last 14.5M run I did, and it would take a couple of days to run that one again, but I did some runs at block heights of 1M, 2M, and 5M.  At 1M the progress was a bit jumpy (eg, more variation between the workers, and occasional sudden leaps), but at 5M it was fairly steady.  At what was the actual half-way point (135 minutes) it averaged ~67% overall but a few of the workers were far back (~20%).  Worker 8 showed the most "jumpy" behavior, quickly moving from 25% to 94% over the course of an hour, and worker 2 the most sluggish.  It actually took the longest, taking another 135 minutes to move from 62% to 100%.

Overall though I would say it accomplishes the "reasonable estimate" goal.  After it had been running for half an hour, I looked at the progress and guessed it would take it 5h.  It took 4:29:15.

**Comment by telackey** [comment]
By the way, I made those changes _before_ the last two comments by Ian and David, I just wanted to update the conversation.

**Pull request merged**
